# .env variable names
OPEN_AI_KEY='OPEN_AI_KEY'
WEAVIATE_API_KEY='WEAVIATE_API_KEY'
WEAVIATE_CLUSTER_URL='WEAVIATE_CLUSTER_URL'
DISCORD_TOKEN='DISCORD_TOKEN'
DISCORD_GUILD_ID='DISCORD_GUILD_ID'
TEST_GUILD_ID='TEST_GUILD_ID'
TEST_MODE='TEST_MODE'